ADDRESS = ("localhost", 18374)

MOVE = "MOVE"
ROTATE = "ROTATE"
GET_LOCATION = "GET_LOCATION"
GET_BEARING = "GET_BEARING"
SHOOT = "SHOOT"
TURN_TO = "TURN_TO"
MOVE_TO = "MOVE_TO"
GENERATE_TARGETS = "GENERATE_TARGETS"
GET_SHOOTABLE_TARGETS = "GET_SHOOTABLE_TARGETS"
GET_TREADABLE_TARGETS = "GET_TREADABLE_TARGETS"
